export const CategoryMasterList = [
  { id: 1, name: "Laptops", state: 1 },
  { id: 2, name: "Desktop Computers", state: 1 },
  { id: 3, name: "Monitors", state: 1 },
  { id: 4, name: "Keyboards", state: 1 },
  { id: 5, name: "Mouse", state: 1 },
  { id: 6, name: "Printers", state: 1 },
  { id: 7, name: "Scanners", state: 1 },
  { id: 8, name: "Projectors", state: 1 },
  { id: 9, name: "Webcams", state: 1 },
  { id: 10, name: "Headphones & Audio", state: 1 },
  { id: 11, name: "Storage Devices", state: 1 },
  { id: 12, name: "Memory (RAM)", state: 1 },
  { id: 13, name: "Processors (CPU)", state: 1 },
  { id: 14, name: "Motherboards", state: 1 },
  { id: 15, name: "Graphics Cards (GPU)", state: 1 },
  { id: 16, name: "Power Supplies (PSU)", state: 1 },
  { id: 17, name: "Computer Cases", state: 1 },
  { id: 18, name: "Cooling Systems", state: 1 },
  { id: 19, name: "Networking Devices", state: 1 },
  { id: 20, name: "Cables & Connectivity", state: 1 },
  { id: 21, name: "Laptop Accessories", state: 1 },
  { id: 22, name: "Power & Backup", state: 1 },
  { id: 23, name: "Office Equipment", state: 1 },
  { id: 24, name: "Software", state: 1 },
  { id: 25, name: "Security & Surveillance", state: 1 },
  { id: 26, name: "Cleaning & Maintenance", state: 1 },
  { id: 27, name: "Adapters & Converters", state: 1 },
  { id: 28, name: "Peripheral Accessories", state: 1 },
  { id: 29, name: "Gaming Accessories", state: 1 },
  { id: 30, name: "Other Accessories", state: 1 },
];
